Models/Flight.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace proekt1.Models
{
    public class Flight
    {
        [Key]
        public int FlightID { get; set; }

        [Required]
        public string StartLocation { get; set; }

        [Required]
        public string EndLocation { get; set; }

        [Required]
        [DateGreaterThanToday]
        public DateTime StartDateTime { get; set; }

        [Required]
        [DateGreaterThanToday]
        public DateTime EndDateTime { get; set; }

        [Required]
        public string PilotName { get; set; }

        public int PlaneID { get; set; }
        [ForeignKey("PlaneID")]
        public Plane? Plane { get; set; }
        public virtual ICollection<Reservation>? Reservations { get; set; } = new List<Reservation>();


        
      
    }
}

Controllers/FlightsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using Microsoft.EntityFrameworkCore;
using proekt1.Data;
using proekt1.Models;

namespace proekt1.Controllers
{
    //promqna
    [Authorize(Roles = "admin,employee")]
    public class FlightsController : Controller
    {
        private readonly proekt1Context _context;

        public FlightsController(proekt1Context context)
        {
            _context = context;
        }

        // GET: Flights
        [AllowAnonymous]
        public async Task<IActionResult> Index(string searchTerm)
        {
            //if(User.IsInRole("admin") || User.IsInRole("emoloyee"))
            //{
            var flights = from n in _context.Flight.Include(f => f.Plane) select n; // Get all notes

            if (!string.IsNullOrEmpty(searchTerm))
            {
                flights = flights.Where(n => n.StartLocation.Contains(searchTerm) || n.EndLocation.Contains(searchTerm) || n.StartDateTime.ToString().Contains(searchTerm) || n.EndDateTime.ToString().Contains(searchTerm));
            }
            ViewData["SearchTerm"] = searchTerm;
            //var proekt1Context = _context.Flight.Include(f => f.Plane);
                return View(await flights.ToListAsync());
            //}
            //else
            //{
            //    var proekt1Context = _context.Flight.Include(f => f.Plane);
            //    var availableFlights = new List<Flight>();
            //    foreach(var flight in proekt1Context)
            //    {
            //        if(flight.Reservations.Count != 0)
            //        {
            //            if(flight.Reservations.Count != flight.Plane.MaxSeats + flight.Plane.MaxBusinessSeats)
            //            {
            //                availableFlights.Add(flight);
            //            }
            //        }
            //    }
            //    return View(availableFlights);
            //}
            
        }

        // GET: Flights/Details/5
        [AllowAnonymous]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight
                .Include(f => f.Plane)
                .Include(r => r.Reservations)
                .FirstOrDefaultAsync(m => m.FlightID == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // GET: Flights/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["PlaneID"] = new SelectList(_context.Plane, "PlaneID", "PlaneID");
            return View();
        }

        // POST: Flights/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Create([Bind("FlightID,StartLocation,EndLocation,StartDateTime,EndDateTime,PilotName,PlaneID")] Flight flight)
        {
            if (ModelState.IsValid)
            {
                _context.Add(flight);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlaneID"] = new SelectList(_context.Plane, "PlaneID", "PlaneID", flight.PlaneID);
            return View(flight);
        }

        // GET: Flights/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight.FindAsync(id);
            if (flight == null)
            {
                return NotFound();
            }
            ViewData["PlaneID"] = new SelectList(_context.Plane, "PlaneID", "PlaneID", flight.PlaneID);
            return View(flight);
        }

        // POST: Flights/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FlightID,StartLocation,EndLocation,StartDateTime,EndDateTime,PilotName,PlaneID")] Flight flight)
        {
            if (id != flight.FlightID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(flight);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FlightExists(flight.FlightID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PlaneID"] = new SelectList(_context.Plane, "PlaneID", "PlaneID", flight.PlaneID);
            return View(flight);
        }

        // GET: Flights/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var flight = await _context.Flight
                .Include(f => f.Plane)
                .FirstOrDefaultAsync(m => m.FlightID == id);
            if (flight == null)
            {
                return NotFound();
            }

            return View(flight);
        }

        // POST: Flights/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var flight = await _context.Flight.FindAsync(id);
            if (flight != null)
            {
                _context.Flight.Remove(flight);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        
        private bool FlightExists(int id)
        {
            return _context.Flight.Any(e => e.FlightID == id);
        }
    }
}

Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using proekt1.Data;
using proekt1.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.WebUtilities;
using System.Text.Encodings.Web;
using System.Text;
using Microsoft.AspNetCore.Identity.UI.Services;
using RestSharp;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace proekt1.Controllers
{
    //[Authorize(Roles ="admin,employee")]
    public class ReservationsController : Controller
    {
        private readonly proekt1Context _context;
        private readonly IEmailSender _emailSender;

        public ReservationsController(proekt1Context context, IEmailSender emailSender)
        {
            _context = context;
            _emailSender = emailSender;
        }

        // GET: Reservations
        public async Task<IActionResult> Index()
        {
            var proekt1Context = _context.Reservation.Include(r => r.Flight).Include(r => r.User);
            return View(await proekt1Context.ToListAsync());
        }

        // GET: Reservations/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.Flight)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReservationID == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // GET: Reservations/Create

        //[AllowAnonymous]
        public IActionResult Create(int? FlightID)
        {
            ViewData["FlightID"] = new SelectList(_context.Flight, "FlightID", "EndLocation");
            ViewData["UserEmail"] = new SelectList(_context.Set<Person>(), "Id", "Id");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ReservationID,FirstName,MiddleName,LastName,Email,EGN,Phone,TicketType,FlightID")] Reservation reservation)
        {
            var flight = await _context.Flight.FirstOrDefaultAsync(x => x.FlightID == reservation.FlightID);
            reservation.PlaneID = flight.PlaneID;
            if (ModelState.IsValid)
            {
                _context.Add(reservation);
                //AddReservation(flight.FlightID, reservation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index", "Home", new { area = "" });
            }
            ViewData["FlightID"] = new SelectList(_context.Flight, "FlightID", "EndLocation", reservation.FlightID);
            ViewData["UserEmail"] = new SelectList(_context.Set<Person>(), "Id", "Id", reservation.UserEmail);

            return View(reservation);
        }
        

        // GET: Reservations/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation.FindAsync(id);
            if (reservation == null)
            {
                return NotFound();
            }
            ViewData["FlightID"] = new SelectList(_context.Flight, "FlightID", "EndLocation", reservation.FlightID);
            ViewData["UserEmail"] = new SelectList(_context.Set<Person>(), "Id", "Id", reservation.UserEmail);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ReservationID,FirstName,MiddleName,LastName,Email,EGN,Phone,TicketType,FlightID")] Reservation reservation)
        {
            if (id != reservation.ReservationID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(reservation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ReservationExists(reservation.ReservationID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FlightID"] = new SelectList(_context.Flight, "FlightID", "EndLocation", reservation.FlightID);
            ViewData["UserEmail"] = new SelectList(_context.Set<Person>(), "Id", "Id", reservation.UserEmail);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var reservation = await _context.Reservation
                .Include(r => r.Flight)
                .Include(r => r.User)
                .FirstOrDefaultAsync(m => m.ReservationID == id);
            if (reservation == null)
            {
                return NotFound();
            }

            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var reservation = await _context.Reservation.FindAsync(id);
            if (reservation != null)
            {
                _context.Reservation.Remove(reservation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ReservationExists(int id)
        {
            return _context.Reservation.Any(e => e.ReservationID == id);
        }
    }
}

Views/Flights/Create.cshtml
@model proekt1.Models.Flight

<style>
    body {
        background-color: #fff1d5;
    }
</style>
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="StartLocation" class="control-label"></label>
                <input asp-for="StartLocation" class="form-control" />
                <span asp-validation-for="StartLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndLocation" class="control-label"></label>
                <input asp-for="EndLocation" class="form-control" />
                <span asp-validation-for="EndLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime" class="control-label"></label>
                <input asp-for="StartDateTime" class="form-control" />
                <span asp-validation-for="StartDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDateTime" class="control-label"></label>
                <input asp-for="EndDateTime" class="form-control" />
                <span asp-validation-for="EndDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PilotName" class="control-label"></label>
                <input asp-for="PilotName" class="form-control" />
                <span asp-validation-for="PilotName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneID" class="control-label"></label>
                <select asp-for="PlaneID" class ="form-control" asp-items="ViewBag.PlaneID"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Flights/Delete.cshtml
@model proekt1.Models.Flight
<style>
    body {
        background-color: #fff1d5;
    }
</style>
@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plane)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plane.PlaneID)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FlightID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Flights/Details.cshtml
@model proekt1.Models.Flight
<style>
    body {
        background-color: #fff1d5;
    }
</style>
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Flight</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndLocation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndLocation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PilotName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PilotName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plane)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plane.PlaneID)
        </dd>
        @* promqna *@
        @if(User.IsInRole("admin")||User.IsInRole("employee"))
        {
            <dt class="col-sm-2">
                Reservations
            </dt>
            @if (Model.Reservations.Count != 0)
            {
                <table class="table">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Middle Name</th>
                            <th>Last Name</th>
                            <th>Email</th>
                            <th>EGN</th>
                            <th>Phone</th>
                            <th>Ticket Type</th>
                            @* 
                        <th>
                            @Html.DisplayNameFor(model => model.Flight)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.User)
                        </th> *@
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>

                        @foreach (var item in Model.Reservations)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MiddleName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Email)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.EGN)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Phone)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.TicketType)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Flight.EndLocation)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.User.Id)
                                </td>
                                <td>
                                    <a asp-controller="Reservations" asp-action="Edit" asp-route-id="@item.ReservationID">Edit</a> |
                                    <a asp-controller="Reservations" asp-action="Details" asp-route-id="@item.ReservationID">Details</a> |
                                    <a asp-controller="Reservations" asp-action="Delete" asp-route-id="@item.ReservationID">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
            else
            {
                <th>There are no reservations</th>
            }
            
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FlightID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Flights/Edit.cshtml
@model proekt1.Models.Flight
<style>
    body {
        background-color: #fff1d5;
    }
</style>
@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Flight</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FlightID" />
            <div class="form-group">
                <label asp-for="StartLocation" class="control-label"></label>
                <input asp-for="StartLocation" class="form-control" />
                <span asp-validation-for="StartLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndLocation" class="control-label"></label>
                <input asp-for="EndLocation" class="form-control" />
                <span asp-validation-for="EndLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDateTime" class="control-label"></label>
                <input asp-for="StartDateTime" class="form-control" />
                <span asp-validation-for="StartDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDateTime" class="control-label"></label>
                <input asp-for="EndDateTime" class="form-control" />
                <span asp-validation-for="EndDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PilotName" class="control-label"></label>
                <input asp-for="PilotName" class="form-control" />
                <span asp-validation-for="PilotName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlaneID" class="control-label"></label>
                <select asp-for="PlaneID" class="form-control" asp-items="ViewBag.PlaneID"></select>
                <span asp-validation-for="PlaneID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Flights/Index.cshtml
@model IEnumerable<proekt1.Models.Flight>
<style>
    body {
        background-color: #fff1d5;
    }
</style>
@{
    ViewData["Title"] = "Index";
}
@using (Html.BeginForm("Index", "Flights", FormMethod.Get))
{
    <form>
        <input type="text" name="searchTerm" style="width: 70%; height:40px;" placeholder="Search notes..." value="@ViewData["SearchTerm"]" />
        <button type="submit" class="btn btn-primary ">Search</button>
    </form>

}

@if(User.IsInRole("admin"))
{
    <h1>Index</h1>
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<h4>Available flights</h4>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.StartLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StartDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EndDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PilotName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plane)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
            @if(item.StartDateTime >= DateTime.Now)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartLocation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndLocation)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.EndDateTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PilotName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Plane.PlaneID)
                    </td>
                    @if(User.IsInRole("admin")||User.IsInRole("employee"))
                    {
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.FlightID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.FlightID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.FlightID">Delete</a> |
                            @* promqna *@
                            <a asp-area="" asp-controller="Reservations" asp-action="Create" asp-route-FlightID="@item.FlightID">Reserve</a>
                        </td>
                    }
                    else
                    {
                        <td>
                            <a asp-action="Details" asp-route-id="@item.FlightID">Details</a> |
                            @* promqna *@
                            <a asp-area="" asp-controller="Reservations" asp-action="Create" asp-route-FlightID="@item.FlightID">Reserve</a>
                        </td>
                    }
                    
                </tr>
    }
        
}
    </tbody>
</table>
@if(User.IsInRole("emaployee") || User.IsInRole("admin"))
{
    <h4>Past flights</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.StartLocation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndLocation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StartDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDateTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PilotName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Plane)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.StartDateTime < DateTime.Now)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartLocation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndLocation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndDateTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PilotName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Plane.PlaneID)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.FlightID">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.FlightID">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.FlightID">Delete</a> |
                            @* promqna *@
                            <a asp-area="" asp-controller="Reservations" asp-action="Create" asp-route-FlightID="@item.FlightID">Reserve</a>
                        </td>
                    </tr>
                }

            }
        </tbody>
    </table>
}